"""Generate or verify the collected pytest inventory used by test documentation."""

from __future__ import annotations

import argparse
import ast
import contextlib
import io
from collections import Counter
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
DESTINATION = ROOT / "docs" / "rules_engine_test_inventory.md"


class Inventory:
    """Collect case counts without running tests or creating a Spark session."""

    def __init__(self):
        self.cases: Counter[str] = Counter()
        self.live_spark: Counter[str] = Counter()

    def pytest_collection_finish(self, session):
        for item in session.items:
            name = item.path.name
            self.cases[name] += 1
            if "spark" in item.fixturenames:
                self.live_spark[name] += 1


def render_inventory(inventory: Inventory) -> str:
    """Render stable counts derived from collected cases and test definitions."""
    lines = [
        "# Rules Engine Test Inventory",
        "",
        "Generated by `python scripts/test_inventory.py`; CI checks this file for drift.",
        "Counts describe collected cases, not a record of successful execution.",
        "Live Spark cases require `RULES_ENGINE_RUN_SPARK_TESTS=1` and Java.",
        "The Databricks system notebook is a separate acceptance suite.",
        "",
        "| Test module | Explicit functions | Collected cases | Live Spark cases |",
        "| --- | ---: | ---: | ---: |",
    ]
    explicit_total = 0
    for name, cases in sorted(inventory.cases.items()):
        tree = ast.parse((ROOT / "tests" / name).read_text(encoding="utf-8"))
        explicit = sum(
            isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef))
            and node.name.startswith("test_")
            for node in ast.walk(tree)
        )
        explicit_total += explicit
        lines.append(
            f"| [{name}](../tests/{name}) | {explicit} | {cases} | "
            f"{inventory.live_spark[name]} |"
        )
    lines.extend([
        f"| **Total** | **{explicit_total}** | **{sum(inventory.cases.values())}** | "
        f"**{sum(inventory.live_spark.values())}** |",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if documentation is stale.")
    args = parser.parse_args()
    inventory = Inventory()
    captured = io.StringIO()
    with contextlib.redirect_stdout(captured), contextlib.redirect_stderr(captured):
        code = pytest.main(
            [str(ROOT / "tests"), "--collect-only", "-q", "-p", "no:cacheprovider"],
            plugins=[inventory],
        )
    if code != pytest.ExitCode.OK:
        print(captured.getvalue())
        return int(code)
    expected = render_inventory(inventory)
    if args.check:
        if not DESTINATION.is_file() or DESTINATION.read_text(encoding="utf-8") != expected:
            print("Test inventory is stale. Run: python scripts/test_inventory.py")
            return 1
        print("Test documentation inventory is current.")
    else:
        DESTINATION.write_text(expected, encoding="utf-8", newline="\n")
        print(f"Updated {DESTINATION.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
